package IGU;

import bibliotecabd.ConexionMongo;
import com.mongodb.client.MongoDatabase;
import dao.LibroDAO;
import dao.PrestamoDAO;
import dao.UsuarioDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Libro;
import model.Usuario;
import modelo.Prestamo;

public class GestionPrestamosFrame extends javax.swing.JFrame {

    MongoDatabase database = ConexionMongo.getDatabase();
    PrestamoDAO prestamoDAO = new PrestamoDAO(database);
    UsuarioDAO usuarioDAO = new UsuarioDAO();     
    LibroDAO libroDAO = new LibroDAO();      

    public GestionPrestamosFrame() {
        initComponents();
        cargarUsuarios();
        cargarLibros();
        cargarTablaPrestamos();
    }
    

   // ========================= CARGAR USUARIOS =============================
    private void cargarUsuarios() {
        cmbUsuarios.removeAllItems();
        for(Usuario u : usuarioDAO.obtenerTodos()){
            cmbUsuarios.addItem(u.getId() + " - " + u.getNombre());
        }
    }

    // ========================= CARGAR LIBROS ===============================
    private void cargarLibros() {
        cmbLibros.removeAllItems();
        for(Libro l : libroDAO.obtenerTodos()){
            cmbLibros.addItem(l.getId() + " - " + l.getTitulo());
        }
    }

    // ========================= REGISTRAR PRESTAMO ==========================
    private void registrarPrestamo(){

        if(cmbUsuarios.getSelectedItem()==null || cmbLibros.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this,"Seleccione usuario y libro");
            return;
        }

        String idUsuario = cmbUsuarios.getSelectedItem().toString().split(" - ")[0];
        String idLibro   = cmbLibros.getSelectedItem().toString().split(" - ")[0];

        if(prestamoDAO.libroEstaPrestado(idLibro)){
            JOptionPane.showMessageDialog(this,"❌ Ese libro ya está prestado");
            return;
        }

        Prestamo p = new Prestamo(null,idUsuario,idLibro,txtFechaPrestamo.getText(),"",false);

        if(prestamoDAO.registrarPrestamo(p)){
            JOptionPane.showMessageDialog(this,"✔ Préstamo registrado");
            cargarTablaPrestamos();
        }
    }

    // ========================= DEVOLVER PRESTAMO ===========================
    private void devolverPrestamo(){

        int fila = tablaPrestamos.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(this,"Seleccione un préstamo de la tabla");
            return;
        }

        String idPrestamo = tablaPrestamos.getValueAt(fila,0).toString();

        if(prestamoDAO.marcarComoDevuelto(idPrestamo)){
            JOptionPane.showMessageDialog(this,"📗 Préstamo devuelto");
            cargarTablaPrestamos();
        }
    }

    // ========================= CARGAR TABLA ================================
    private void cargarTablaPrestamos(){

        DefaultTableModel modelo = new DefaultTableModel();
    modelo.setColumnIdentifiers(new String[]{"ID", "Usuario", "Libro", "Fecha Préstamo", "Devuelto"});

    for (Prestamo p : prestamoDAO.obtenerTodos()) {

        // usuario
        Usuario u = usuarioDAO.buscarPorId(p.getIdUsuario());
        String nomUsuario = (u != null) ? u.getNombre() : "DESCONOCIDO";

        // libro
        Libro l = libroDAO.buscarPorId(p.getIdLibro());
        String nomLibro = (l != null) ? l.getTitulo() : "DESCONOCIDO";

        modelo.addRow(new Object[]{
            p.getId(),
            nomUsuario,
            nomLibro,
            p.getFechaPrestamo(),
            p.isDevuelto() ? "Sí" : "No"
        });
    }

    tablaPrestamos.setModel(modelo);

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbUsuarios = new javax.swing.JComboBox<>();
        cmbLibros = new javax.swing.JComboBox<>();
        txtFechaPrestamo = new javax.swing.JTextField();
        btnPrestar = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        jScrollPanePrestamos = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPrestamos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        cmbUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbLibros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnPrestar.setText("REGISTRAR PRESTAMO");

        btnDevolver.setText("DEVOLVER PRESTAMO");

        tablaPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPrestamos);

        jScrollPanePrestamos.add(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDevolver)
                    .addComponent(btnPrestar)
                    .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbUsuarios, javax.swing.GroupLayout.Alignment.LEADING, 0, 109, Short.MAX_VALUE)
                        .addComponent(cmbLibros, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPanePrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnPrestar)
                        .addGap(18, 18, 18)
                        .addComponent(btnDevolver))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPanePrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPrestamosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPrestamosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPrestamosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPrestamosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPrestamosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JComboBox<String> cmbLibros;
    private javax.swing.JComboBox<String> cmbUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.ScrollPane jScrollPanePrestamos;
    private javax.swing.JTable tablaPrestamos;
    private javax.swing.JTextField txtFechaPrestamo;
    // End of variables declaration//GEN-END:variables
}
