package IGU;

import bibliotecabd.ConexionMongo;
import com.mongodb.client.MongoDatabase;
import bibliotecabd.ConexionMongo;
import dao.LibroDAO;
import dao.PrestamoDAO;
import dao.SuscriptorDAO;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Libro;
import modelo.Prestamo;
import model.Suscriptor;

public class GestionPrestamosFrame extends javax.swing.JFrame {
    
    private String formatearFecha(Date fecha) {
    if (fecha == null) return "";
    // Convertimos a LocalDate en UTC para evitar desfases de zona horaria:
    // Primero obtener instant y representarlo en UTC, luego a LocalDate y formatear.
    java.time.LocalDate ld = Instant.ofEpochMilli(fecha.getTime()).atZone(ZoneId.of("UTC")).toLocalDate();
    return ld.toString(); // yyyy-MM-dd
}

    MongoDatabase database = ConexionMongo.getDatabase();
    PrestamoDAO prestamoDAO = new PrestamoDAO(database);
    LibroDAO libroDAO = new LibroDAO();
    SuscriptorDAO suscriptorDAO = new SuscriptorDAO();   

    public GestionPrestamosFrame() {
        initComponents();
        cargarSuscriptores();
        cargarLibros();
        cargarTablaPrestamos();
        
        // Oculta la columna ID
        tablaPrestamos.getColumnModel().getColumn(0).setMinWidth(0);
        tablaPrestamos.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaPrestamos.getColumnModel().getColumn(0).setWidth(0);

    }
        
    private void cargarSuscriptores() {
        comboSuscriptor.removeAllItems();
        List<Suscriptor> lista = suscriptorDAO.obtenerTodos();
        
        for (Suscriptor s : lista) {
            comboSuscriptor.addItem(s.getDocumento() + " - " + s.getNombre());
        }
    }


    private void cargarLibros() {
        cmbLibros.removeAllItems();
        for(Libro l : libroDAO.obtenerTodos()){
            cmbLibros.addItem(l.getId() + " - " + l.getTitulo());
        }
    }

    private void cargarTablaPrestamos() {
    DefaultTableModel modelo = (DefaultTableModel) tablaPrestamos.getModel();
    // Asegúrate de que la tabla tenga 6 columnas: ID, Suscriptor, Libro, Fecha Prestamo, Fecha Devolucion, Devuelto
    modelo.setRowCount(0);

    for (Prestamo p : prestamoDAO.obtenerTodos()) {
        Suscriptor s = suscriptorDAO.buscarPorId(p.getIdSuscriptor());
        Libro l = libroDAO.buscarPorId(p.getIdLibro());

        modelo.addRow(new Object[]{
            p.getId(),
            (s != null ? s.getNombre() : "DESCONOCIDO"),
            (l != null ? l.getTitulo() : "DESCONOCIDO"),
            formatearFecha(p.getFechaPrestamo()),
            formatearFecha(p.getFechaDevolucion()),
            p.isDevuelto() ? "Sí" : "No"
        });
    }
}

    private void registrarPrestamo() {

    if (comboSuscriptor.getSelectedItem() == null || cmbLibros.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Seleccione suscriptor y libro");
        return;
    }

    // Obtener documento del suscriptor
    String documentoSuscriptor = comboSuscriptor.getSelectedItem().toString().split(" - ")[0];

    // Obtener código del libro
    String idLibro = cmbLibros.getSelectedItem().toString().split(" - ")[0];

    // Verificar si el libro está prestado
    if (prestamoDAO.libroEstaPrestado(idLibro)) {
        JOptionPane.showMessageDialog(this, "❌ Ese libro ya está prestado");
        return;
    }

    // Crear objeto Prestamo
    Prestamo p = new Prestamo();
    p.setIdUsuario("admin");
    p.setIdSuscriptor(documentoSuscriptor);
    p.setIdLibro(idLibro);
    p.setFechaPrestamo(new Date());
    p.setFechaDevolucion(null);
    p.setDevuelto(false);

    // Guardar en Mongo
    if (prestamoDAO.registrarPrestamo(p)) {
        JOptionPane.showMessageDialog(this, "✔ Préstamo registrado con éxito");
        cargarTablaPrestamos();
    } else {
        JOptionPane.showMessageDialog(this, "❌ Error registrando el préstamo");
    }
}

    private void devolverPrestamo() {
    int fila = tablaPrestamos.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un préstamo");
        return;
    }

    String idPrestamo = tablaPrestamos.getValueAt(fila, 0).toString();

    boolean exito = prestamoDAO.marcarComoDevuelto(idPrestamo);

    if (exito) {
        JOptionPane.showMessageDialog(this, "Préstamo marcado como devuelto.");
        cargarTablaPrestamos();
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo devolver el préstamo.");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbLibros = new javax.swing.JComboBox<>();
        btnPrestar = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        jScrollPanePrestamos = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPrestamos = new javax.swing.JTable();
        comboSuscriptor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        cmbLibros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnPrestar.setText("REGISTRAR PRESTAMO");
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        btnDevolver.setText("DEVOLVER PRESTAMO");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        tablaPrestamos.setModel(new DefaultTableModel(
            new Object[][] {},
            new String[] {
                "ID", "Suscriptor", "Libro", "Fecha Préstamo", "Fecha Devolución", "Devuelto"
            }
        ));
        jScrollPane1.setViewportView(tablaPrestamos);

        jScrollPanePrestamos.add(jScrollPane1);

        comboSuscriptor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbLibros, javax.swing.GroupLayout.Alignment.TRAILING, 0, 167, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnDevolver)
                        .addComponent(btnPrestar))
                    .addComponent(comboSuscriptor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPanePrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(comboSuscriptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(cmbLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btnPrestar)
                        .addGap(18, 18, 18)
                        .addComponent(btnDevolver))
                    .addComponent(jScrollPanePrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
       registrarPrestamo();
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        devolverPrestamo();
    }//GEN-LAST:event_btnDevolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPrestamosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPrestamosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPrestamosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPrestamosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPrestamosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JComboBox<String> cmbLibros;
    private javax.swing.JComboBox<String> comboSuscriptor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.ScrollPane jScrollPanePrestamos;
    private javax.swing.JTable tablaPrestamos;
    // End of variables declaration//GEN-END:variables
}
